"""add cover_image_url to article

Revision ID: 29e71037b490
Revises: 80530c2ac821
Create Date: 2026-09-25 10:58:45.407526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e71037b490'
down_revision: Union[str, Sequence[str], None] = '80530c2ac821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'cover_image_url')
    # ### end Alembic commands ###
