"""add subject to contact_messages

Revision ID: 80530c2ac821
Revises: 9711c6410af5
Create Date: 2026-09-24 13:50:22.921969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80530c2ac821'
down_revision: Union[str, Sequence[str], None] = '9711c6410af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_messages', sa.Column('subject', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_messages', 'subject')
    # ### end Alembic commands ###
